apiVersion: v1
kind: Pod

metadata:
  name: chatgpt-app3

spec:
  containers:
    - name: chatgpt-app3
      image: chatgpt-app3:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
      env:
        - name: ENVIRONMENT
          value: development
